<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjUG7iq\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjUG7iq/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXjUG7iq.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXjUG7iq\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXjUG7iq\App_KernelProdContainer([
    'container.build_hash' => 'XjUG7iq',
    'container.build_id' => 'b1c5a9d2',
    'container.build_time' => 1635162174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjUG7iq');
