<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BGreUoIService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bGreUoI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bGreUoI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'User' => ['privates', '.errored..service_locator.bGreUoI.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.bGreUoI": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'User' => 'App\\Entity\\User',
        ]);
    }
}
