<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGGEQcpService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.aGGEQcp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aGGEQcp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Calendar' => ['privates', '.errored..service_locator.aGGEQcp.App\\Entity\\Calendar', NULL, 'Cannot autowire service ".service_locator.aGGEQcp": it references class "App\\Entity\\Calendar" but no such service exists.'],
        ], [
            'Calendar' => 'App\\Entity\\Calendar',
        ]);
    }
}
