<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdministratorControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdministratorController' shared autowired service.
     *
     * @return \App\Controller\AdministratorController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdministratorController'] = $instance = new \App\Controller\AdministratorController(($container->privates['App\\Notification\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->privates['App\\Service\\Mailjet'] ?? $container->load('getMailjetService')));

        $instance->setContainer(($container->privates['.service_locator.jG2fmhC'] ?? $container->load('get_ServiceLocator_JG2fmhCService'))->withContext('App\\Controller\\AdministratorController', $container));

        return $instance;
    }
}
