<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourseControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CourseController' shared autowired service.
     *
     * @return \App\Controller\CourseController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CourseController'] = $instance = new \App\Controller\CourseController(($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\Mailjet'] ?? $container->load('getMailjetService')), ($container->privates['App\\Notification\\NotificationService'] ?? $container->load('getNotificationServiceService')));

        $instance->setContainer(($container->privates['.service_locator.jG2fmhC'] ?? $container->load('get_ServiceLocator_JG2fmhCService'))->withContext('App\\Controller\\CourseController', $container));

        return $instance;
    }
}
