<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditLanguageCategoryTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EditLanguageCategoryType' shared autowired service.
     *
     * @return \App\Form\EditLanguageCategoryType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EditLanguageCategoryType'] = new \App\Form\EditLanguageCategoryType();
    }
}
