<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageProgramationCategoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LanguageProgramationCategoryRepository' shared autowired service.
     *
     * @return \App\Repository\LanguageProgramationCategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LanguageProgramationCategoryRepository'] = new \App\Repository\LanguageProgramationCategoryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
