<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MessengerType' shared autowired service.
     *
     * @return \App\Form\MessengerType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MessengerType'] = new \App\Form\MessengerType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
