<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.EcRFATP.App\Entity\Message' shared service.
     *
     * @return \App\Entity\Message
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EcRFATP": it references class "App\\Entity\\Message" but no such service exists.');
    }
}
