<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MessengerController' shared autowired service.
     *
     * @return \App\Controller\MessengerController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MessengerController'] = $instance = new \App\Controller\MessengerController(new \App\Message\MessageService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))));

        $instance->setContainer(($container->privates['.service_locator.jG2fmhC'] ?? $container->load('get_ServiceLocator_JG2fmhCService'))->withContext('App\\Controller\\MessengerController', $container));

        return $instance;
    }
}
