<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Notification\NotificationService' shared autowired service.
     *
     * @return \App\Notification\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Notification\\NotificationService'] = new \App\Notification\NotificationService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
