<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoteTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\NoteType' shared autowired service.
     *
     * @return \App\Form\NoteType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\NoteType'] = new \App\Form\NoteType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
