<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemunerationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RemunerationType' shared autowired service.
     *
     * @return \App\Form\RemunerationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RemunerationType'] = new \App\Form\RemunerationType();
    }
}
