<?php

namespace ContainerXjUG7iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSession2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.3fDzOhi.App\Entity\Session' shared service.
     *
     * @return \App\Entity\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3fDzOhi": it references class "App\\Entity\\Session" but no such service exists.');
    }
}
