<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kh_3AgnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kh.3Agn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kh.3Agn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendar' => ['privates', '.errored..service_locator.kh.3Agn.App\\Entity\\Calendar', NULL, 'Cannot autowire service ".service_locator.kh.3Agn": it references class "App\\Entity\\Calendar" but no such service exists.'],
        ], [
            'calendar' => 'App\\Entity\\Calendar',
        ]);
    }
}
