<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T1AhrzdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T1Ahrzd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T1Ahrzd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'courses' => ['privates', '.errored..service_locator.T1Ahrzd.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.T1Ahrzd": it references class "App\\Entity\\Course" but no such service exists.'],
        ], [
            'courses' => 'App\\Entity\\Course',
        ]);
    }
}
