<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3fDzOhiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3fDzOhi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3fDzOhi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Session' => ['privates', '.errored..service_locator.3fDzOhi.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.3fDzOhi": it references class "App\\Entity\\Session" but no such service exists.'],
        ], [
            'Session' => 'App\\Entity\\Session',
        ]);
    }
}
