<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HUjViokService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hUjViok' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hUjViok'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'techno' => ['privates', '.errored..service_locator.hUjViok.App\\Entity\\LanguageProgramationCategory', NULL, 'Cannot autowire service ".service_locator.hUjViok": it references class "App\\Entity\\LanguageProgramationCategory" but no such service exists.'],
        ], [
            'slugger' => '?',
            'techno' => 'App\\Entity\\LanguageProgramationCategory',
        ]);
    }
}
