<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourse2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qngw_AN.App\Entity\Course' shared service.
     *
     * @return \App\Entity\Course
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qngw_AN": it references class "App\\Entity\\Course" but no such service exists.');
    }
}
