<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageProgramationCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hUjViok.App\Entity\LanguageProgramationCategory' shared service.
     *
     * @return \App\Entity\LanguageProgramationCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hUjViok": it references class "App\\Entity\\LanguageProgramationCategory" but no such service exists.');
    }
}
