<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MessengerController' shared autowired service.
     *
     * @return \App\Controller\MessengerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MessengerController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Message'.\DIRECTORY_SEPARATOR.'AbstractMessage.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Message'.\DIRECTORY_SEPARATOR.'MessageService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['App\\Controller\\MessengerController'] = $instance = new \App\Controller\MessengerController(new \App\Message\MessageService($a), $a);

        $instance->setContainer(($container->privates['.service_locator.ExyJkET'] ?? $container->load('get_ServiceLocator_ExyJkETService'))->withContext('App\\Controller\\MessengerController', $container));

        return $instance;
    }
}
