<?php

namespace ContainerCJYHM3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Notification\NotificationService' shared autowired service.
     *
     * @return \App\Notification\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Notification'.\DIRECTORY_SEPARATOR.'AbstractNotification.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Notification'.\DIRECTORY_SEPARATOR.'NotificationService.php';

        return $container->privates['App\\Notification\\NotificationService'] = new \App\Notification\NotificationService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
