<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRtOeDy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRtOeDy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRtOeDy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRtOeDy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXRtOeDy\App_KernelDevDebugContainer([
    'container.build_hash' => 'XRtOeDy',
    'container.build_id' => 'ad30a979',
    'container.build_time' => 1639578691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRtOeDy');
